### ISSUE TITLE
Shared entities do not have update derived pruning

### ISSUE THREAD

**Issue by thefloweringash** [iknow/iknow_view_models#40]
When we touch an entity we want to include our effects in our resulting serialised value. This is implemented by propagating the value of `UpdateData#updated_associations` to the pruning of the serialisation context.

This functionality is simply missing for entities that are modified through a shared relationship. `DeserializeContext#updated_associations` is populated from the root only. The `SerializeContext#serialize_references` method uses `self` as the context for the referenced updates, and leaves no opportunity to use pruning other than the root pruning.

**Comment by chrisandreae** [comment]
We no longer want pruning as a feature, wontfix
