### ISSUE TITLE
References can't have prune/include

### ISSUE THREAD

**Issue by thefloweringash** [iknow/iknow_view_models#80]
There's a single context for all reference serialisations (via `SerializeContext#for_references`), which prevents specifying `prune` or `include`. We'd have to allow the `prune` and `include` to be parameterised by type. This could be in terms of a prune/include tree by root type, or a flattened context-free specification per type. While we're here, make sure that the `changed_association` propagation works with references.

**Comment by chrisandreae** [comment]
We no longer want pruning as a feature, wontfix
